version: '3.7'

services:    
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    container_name: ${container_name}
    image: 'corgiinspace-frontend'
    environment:
      - STAG
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
    networks:
      - development
networks:
  development:
    driver: bridge
